#!/bin/bash
#-------------------------
# Testing client utilities
#-------------------------
set -e

HELP_CLIENTS=('swift')
for client in "${HELP_CLIENTS[@]}"; do
    if ! $client -h 2>&1 > /dev/null; then
        echo "ERROR, ${client} is not running"
        exit 1
    else
        echo "OK: ${client} is running"
    fi
done
exit 0
